# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: country_codes 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "country_codes"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Zachary Powell"]
  s.date = "2015-05-28"
  s.email = "zach@babelian.net"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = "http://github.com/pledgemusic/country_codes"
  s.rubygems_version = "2.2.2"
  s.summary = "Country and Postcode information"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 3.0.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["= 3.0.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 3.0.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

